import random

PROMPTS = [
    "Who is most likely to forget their own birthday?",
    "Who is most likely to become famous?",
    "Who is most likely to survive a zombie apocalypse?",
    "Who is most likely to cry during a movie?",
    "Who is most likely to sleep through an alarm?",
    "Who is most likely to become a millionaire?",
    "Who is most likely to get lost in their own city?",
    "Who is most likely to eat something off the floor?",
    "Who is most likely to go skydiving?",
    "Who is most likely to win a reality TV show?",
    "Who is most likely to talk their way out of a speeding ticket?",
    "Who is most likely to accidentally send a text to the wrong person?",
    "Who is most likely to start a fight at a bar?",
    "Who is most likely to marry a celebrity?",
    "Who is most likely to be late to their own wedding?",
    "Who is most likely to laugh at the worst possible moment?",
    "Who is most likely to get a tattoo they regret?",
    "Who is most likely to binge an entire series in one day?",
    "Who is most likely to ghost someone?",
    "Who is most likely to go viral on social media?",
    "Who is most likely to drunk-text their ex?",
    "Who is most likely to eat the last slice without asking?",
    "Who is most likely to trip on a flat surface?",
    "Who is most likely to fall asleep at a party?",
    "Who is most likely to survive on a deserted island?",
    "Who is most likely to get arrested for something stupid?",
    "Who is most likely to be a secret genius?",
    "Who is most likely to win a dance battle?",
    "Who is most likely to start a cult accidentally?",
    "Who is most likely to be the first to die in a horror movie?",
    "Who is most likely to forget where they parked?",
    "Who is most likely to have a secret double life?",
    "Who is most likely to adopt 10 cats?",
    "Who is most likely to move to another country?",
    "Who is most likely to become president?",
    "Who is most likely to end up on a true crime podcast?",
    "Who is most likely to still use Facebook?",
    "Who is most likely to win a hot dog eating contest?",
    "Who is most likely to cry at a commercial?",
    "Who is most likely to fake their own death?",
    "Who is most likely to get into an argument with a stranger?",
    "Who is most likely to spend all their money on something useless?",
    "Who is most likely to have the worst hangover?",
    "Who is most likely to break something expensive?",
    "Who is most likely to flirt with a bartender for free drinks?",
    "Who is most likely to show up uninvited?",
    "Who is most likely to be caught talking to themselves?",
    "Who is most likely to have a secret talent nobody knows about?",
    "Who is most likely to get banned from a restaurant?",
    "Who is most likely to say something awkward at the worst time?",
]


def get_random_prompts(n: int = 3) -> list[str]:
    return random.sample(PROMPTS, min(n, len(PROMPTS)))
